// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbEId5umIrY7rOpMccDw229VHjLuTDnQs',
    appId: '1:675552261813:web:eaf3db023194f44c8af0fc',
    messagingSenderId: '675552261813',
    projectId: 'day-quote-5882',
    authDomain: 'day-quote-5882.firebaseapp.com',
    storageBucket: 'day-quote-5882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl330CeitM_KSOK3LnsBvBhQhho0NPExE',
    appId: '1:675552261813:android:d7a8d7b8a483799c8af0fc',
    messagingSenderId: '675552261813',
    projectId: 'day-quote-5882',
    storageBucket: 'day-quote-5882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdH_eM3tVfajyDsUF1ceUJptNfGbeZMIk',
    appId: '1:675552261813:ios:f44f06aeeee31fe58af0fc',
    messagingSenderId: '675552261813',
    projectId: 'day-quote-5882',
    storageBucket: 'day-quote-5882.appspot.com',
    iosClientId: '675552261813-vqt66nc3i55ruel7s5vb15ku8o7btcon.apps.googleusercontent.com',
    iosBundleId: 'com.maciejsulikowski.dayQuote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdH_eM3tVfajyDsUF1ceUJptNfGbeZMIk',
    appId: '1:675552261813:ios:86750249942296b98af0fc',
    messagingSenderId: '675552261813',
    projectId: 'day-quote-5882',
    storageBucket: 'day-quote-5882.appspot.com',
    iosClientId: '675552261813-nkoupokjbjk8l16jqavh9g2nm4qgmkm1.apps.googleusercontent.com',
    iosBundleId: 'com.maciejsulikowski.dayQuote.RunnerTests',
  );
}
